site_name: pybuildingenergy
site_favicon: assets/images/favicon.png
repo_url: https://github.com/EURAC-EEBgroup/pybuildingenergy-docs
theme:
  name: material
  language: en
  logo: assets/images/favicon.png
  # palette:
  #   primary: red
  #   accent: light-grey
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
nav:
  - Home: index.md
  # - Usage: usage.md
  # - API Reference: api.md
  - Quality check: iso_52016_input_check.md
  # - Installation: installation.md
  - Weather data: weather_data.md
  - ISO 52010:
    - ISO 52010 - Calculation procedure: iso_52010.md
  - ISO 52016:
    - ISO 52016 - Introduction: iso_52016.md
    - ISO 52016 - Input: iso_52016_input.md
    - ISO 52016 - Category profiles: iso_52016_categorty_profile.md
    - ISO 52016 - Aggregate Surfaces: iso_52016_aggregate_surface.md
    - ISO 52016 - Adjacent Zone: iso_52016_adj_zone.md
    - ISO 52016 - Ventilation: iso_52016_ventilation.md
    - ISO 52016 - Virtual ground temperature: iso_52016_virtual_ground_temperature.md
    - ISO 52016 - Aeral heat capacity: iso_52016_aeral_heat_capacity.md
    - ISO 52016 - Solar absorption: iso_52016_solar_absorption.md
    - ISO 52016 - Facade elements (nodes): iso_52016_node.md
    # - ISO 52016 - CO2 Equivalent: iso_52016_co2_equivalent.md
    - ISO 52016 - Overall procedure: iso_52016_overall_procedure.md
    
  - ISO 15316:
    - ISO 15316 - Introduction: iso_15316.md
    - ISO 15316 - Input: iso_15316_input.md
    - ISO 15316 - Heating Circuit: iso_15316_heating_circuit.md
    - ISO 15316 - Generation Circuit: iso_15316_generation_circuit.md
    - ISO 15316 - HVAC System inputs: iso_15316_system_inputs.md
    - ISO 15316 - Calculation procedure: iso_15316_calculation_procedure.md
  

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          options:
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: it
          name: Italiano
          build: true
        - locale: en
          name: English
          default: true
          build: true
  - mermaid2


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.snippets


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/css/custom.css


