site_name: pybuildingenergy
repo_url: https://github.com/EURAC-EEBgroup/pybuildingenergy-docs
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
nav:
  - Home: home.md
  - Usage: usage.md
  - API Reference: api.md
  - Quality check: iso_52016_input_check.md
  - Installation: installation.md
  - ISO 52016:
    - ISO 52016 - Introduction: iso_52016.md
  - ISO 15316:
    - ISO 15316 - Introduction: iso_15316.md
    - ISO 15316 - Heating Circuit: iso_15316_heating_circuit.md
    - ISO 15316 - Generation Circuit: iso_15316_generation_circuit.md
    - ISO 15316 - HVAC System inputs: iso_15316_system_inputs.md
    - ISO 15316 - Calculation procedure: iso_15316_calculation_procedure.md
  

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          options:
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: it
          name: Italiano
          build: true
          # Traduzioni delle label di nav (opzionali)
          # nav_translations:
          #   Home: Home
          #   Usage: Utilizzo
          #   "API Reference": "Riferimento API"
          #   "ISO 52016 - Introduction": "ISO 52016 - Introduzione"
          #   "ISO 15316 - Introduction": "ISO 15316 - Introduzione"
          #   "ISO 15316 - Heating Circuit": "ISO 15316 - Circuito di riscaldamento"
          #   "ISO 15316 - Calculation procedure": "ISO 15316 - Procedura di calcolo"
            # Installation: Installazione
        - locale: en
          name: English
          default: true
          build: true
  - mermaid2


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.snippets


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# marmaid:javascript:
#   - https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js
#   - js/mermaid-init.js     # we'll create this file (see below)
# extra_css:
#   - styles/custom.css