site_name: pybuildingenergy
site_url: https://EURAC-EEBgroup.github.io/pybuildingenergy-docs
repo_url: https://github.com/EURAC-EEBgroup/pybuildingenergy-docs
theme:
  name: material
  language: en
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
nav:
  - Home: index.md
  - Usage: en/usage.md
  - API Reference: en/api.md
  - ISO 52016:
    - ISO 52016 - Introduction: en/iso_52016.md
  - ISO 15316:
    - ISO 15316 - Introduction: en/iso_15316.md
    - ISO 15316 - Heating Circuit: en/iso_15316_heating_circuit.md
    - ISO 15316 - Calculation procedure: en/iso_15316_calculation_procedure.md
  - Installation: en/installation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append(".")
          options:
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true
  - i18n:
      docs_structure: folder
      languages:
        - locale: it
          name: Italiano
          default: false   # questa sar√† servita su /
          build: true
          # nav_translations opzionale, es:
          # nav_translations:
          #   Home: Home
        - locale: en
          name: English
          default: true
          build: true
          # nav_translations:
          #   Home: Home


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/custom.css